"""empty message

Revision ID: 197c0bca361e
Revises: da6db025833f
Create Date: 2023-04-17 13:43:36.613255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197c0bca361e'
down_revision = 'da6db025833f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profileicon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=4096),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profileicon',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###